services:
  # mysql 容器
  mysql:
   
    restart: always
    build:
      context: ./docker/mysql #dockerfile文件路径
      dockerfile: Dockerfile #制定dockerfile文件名
      args:
        MYSQL_VERSION: 5.7
    ports:
      - "3307:3306"
    # 环境变量
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 'lightningAbc123qwe'
      MYSQL_USER: 'lightning'
      MYSQL_PASS: 'lightningAbc123qwe'
      MYSQL_DATABASE: 'lightning'
    privileged: true

    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=512M
      --default-authentication-plugin=mysql_native_password
      --sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    working_dir: /var/lib/mysql
    volumes:
      # - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/data:/var/lib/mysql #挂载数据目录到本地
    networks:
        - app_net
  
  # redis 容器
  redis:
    restart: always
    build:
      context: ./docker/redis #dockerfile文件路径
      dockerfile: Dockerfile #制定dockerfile文件名
      args:
        REDIS_VERSION: latest
    ports:
      - "6378:6379"
    volumes:
      - ./redis/data:/data #挂载数据目录到本地
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    
    networks:
        - app_net
  # rabbitmq 容器
  rabbitmq:
    image: rabbitmq:3.8.19-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "123456"
      RABBITMQ_DEFAULT_VHOST: "lightning"
      RABBITMQ_NODENAME: "rabbitmq"
      RABBITMQ_USE_LONGNAME: "true"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia
      - ./rabbitmq/logs:/var/logs
      - ./rabbitmq/conf:/etc/rabbitmq/conf
    networks:
        - app_net
  # php 容器
  php-fpm:
    build:
      context: ./docker/php #dockerfile文件路径
      dockerfile: Dockerfile #制定dockerfile文件名

      args:
        CHANGE_SOURCE: true
        INSTALL_PHPREDIS: true
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - "9000:9000"
      - "9502:9502"
    depends_on:
      - redis
      - mysql
      - rabbitmq
    tmpfs: /var/temp #上传临时文件夹
    working_dir: /home/www
    volumes:
      - ./:/home/www/tea-im-service #服务端
      - ./docker/php/supervisord.d:/etc/supervisord.d
      - ./docker/php/supervisord.conf:/etc/supervisord.conf
      - ./docker/php/logs:/var/log/supervisor
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/php/etc/php.ini:/usr/local/etc/php/php.ini
    command:
      /bin/bash -c "/usr/bin/supervisord -n -c /etc/supervisord.conf"
      chmod -Rf 644 /home/www/tea-im-service/public/storage/files/
    networks:
        - app_net  
  # nginx 容器
  nginx:
    # container_name: tea_im_nginx
    image: 'nginx:alpine'
    # image: daocloud.io/library/nginx:1.19.1-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8078:8078
    # 依赖关系 先跑php
    depends_on:
      - php-fpm
    environment:
      TZ: Asia/Shanghai
    working_dir: /home/www
    volumes_from:
      - php-fpm #继承phpfpm挂载目录
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/log:/etc/nginx/log
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
        - app_net

networks: #网络配置
  app_net: #网络名称
      driver: bridge
volumes:
    mysql:
        driver: local
    redis:
        driver: local

   

