version: "3.3"
services:
  # mysql 容器
  mysql:
    container_name: lightning_mysql #指定容器名
    image: mysql:5.7 #一般电脑可以用这个镜像
#    image: daocloud.io/library/mysql:5.7.5-m15 #M1芯片可以采用这个镜像
    ports:
      - "3307:3306"
    # 环境变量
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_USER: 'lightning'
      MYSQL_PASS: '123456'
      MYSQL_DATABASE: 'webim'
    privileged: true
    command:
       --character-set-server=utf8mb4
       --collation-server=utf8mb4_general_ci
       --explicit_defaults_for_timestamp=true
       --lower_case_table_names=1
       --max_allowed_packet=512M
       --default-authentication-plugin=mysql_native_password
       --sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    working_dir: /var/lib/mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/var/lib/mysql #挂载数据目录到本地
      - ./mysql/log:/var/log/mysql
    networks:
      app_net:
        # 固定子网ip，网段必须在子网络192.168.*.*
        ipv4_address: 192.168.1.10
  # redis 容器
  redis:
    container_name: lightning_redis
    image: 'redis:alpine'
    # image: daocloud.io/library/redis:6.0.5-alpine
    # image: redis:5.0
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      # - ./redis/data:/data #挂载数据目录到本地
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      app_net:
        ipv4_address: 192.168.1.11
  # php 容器
  php-fpm:
    container_name: lightning_php #指定容器名
    # image: phpfpm-image #指定镜像名
#    image: php:8.0.3-fpm  #指定镜像名都可热
    build:
      context: ./php #dockerfile文件路径
      dockerfile: Dockerfile #制定dockerfile文件名
      args:
        CHANGE_SOURCE: true
        INSTALL_PHPREDIS: true
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 9001:9000
    depends_on:
      - redis
      - mysql

    tmpfs: /var/temp #上传临时文件夹
    working_dir: /home/www

    volumes:
      - ../../lightning-service:/home/www/lightning-service #程序运行目录
      - ./php/php-ini-overrides.ini:/etc/php/8.0.3/fpm/conf.d/php8.0.3-overrides.ini
    networks:
      app_net:
        ipv4_address: 192.168.1.12


  # nginx 容器
  nginx:
    container_name: lightning_nginx
    image: 'nginx:alpine'
    # image: daocloud.io/library/nginx:1.19.1-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    # 依赖关系 先跑php
    depends_on:
      - php-fpm
    environment:
      TZ: Asia/Shanghai
    working_dir:  /home/www
    volumes_from:
      - php-fpm #继承phpfpm挂载目录
    hostname: "lighting.gzy"
    volumes:
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/etc/nginx/log
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      app_net:
        ipv4_address: 192.168.1.13
networks: #网络配置
  app_net: #网络名称
    driver: bridge
    ipam: #网络配置
      config:
        - subnet: 192.168.1.0/24 #IP区间
          gateway: 192.168.1.100

