<?php


namespace app\api\dao\room;
use app\api\dao\BaseDao;
use app\model\RoomModel;

class RoomDao extends BaseDao
{

    public function setModel(): string
    {
        // TODO: Implement setModel() method.
        return RoomModel::class;

    }

    public function list(array $where)
    {
        return parent::list($where); // TODO: Change the autogenerated stub

    }


}
